# Generated by Django 4.0.6 on 2022-07-13 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
