# Generated by Django 4.0.6 on 2022-07-13 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0004_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='festival',
            name='venue',
        ),
        migrations.AddField(
            model_name='festival',
            name='venue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivalist_app.venue'),
        ),
    ]
