# Generated by Django 4.0.6 on 2022-07-13 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0006_remove_photo_festival_festival_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='festivalist_app.photo'),
        ),
    ]
