# Generated by Django 4.0.6 on 2022-07-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0007_alter_festival_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='photo',
        ),
        migrations.AddField(
            model_name='festival',
            name='photo',
            field=models.ManyToManyField(to='festivalist_app.photo'),
        ),
    ]
