# Generated by Django 4.0.6 on 2022-07-13 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0010_photo_festival_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='festival',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='festivalist_app.festival'),
        ),
    ]
