# Generated by Django 4.0.6 on 2022-07-13 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0011_remove_festival_photo_photo_festival'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='festival',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivalist_app.festival'),
        ),
    ]
