# Generated by Django 4.0.6 on 2022-07-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0013_remove_photo_festival_festival_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
