# Generated by Django 4.0.6 on 2022-07-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0015_alter_photo_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
