# Generated by Django 4.0.6 on 2022-07-14 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0019_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='festival',
            name='photo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='festivalist_app.photo'),
            preserve_default=False,
        ),
    ]
