# Generated by Django 4.0.6 on 2022-07-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0021_alter_festival_photo_alter_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
