# Generated by Django 4.0.6 on 2022-07-14 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0023_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
