# Generated by Django 4.0.6 on 2022-07-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0025_photo_festival_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='festival',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
