# Generated by Django 4.0.6 on 2022-07-14 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0026_remove_festival_photo_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', max_length=200, upload_to='')),
                ('photo_name', models.CharField(max_length=50)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivalist_app.festival')),
            ],
        ),
    ]
