# Generated by Django 4.0.6 on 2022-07-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0027_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
