# Generated by Django 4.0.6 on 2022-07-14 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivalist_app', '0028_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivalist_app.festival')),
            ],
        ),
    ]
